pipeline {
    // agent any
    agent {
        label "Agent-1"
    }
    stages {
        stage('init') {
            steps {
                sh '''
                    ls -ltr
                    pwd
                    cd 01-VPC
                    terraform init
                '''
                echo "PESI"
            }
        }
        stage('plan') {
            steps {
                sh '''
                    cd 01-VPC
                    terraform plan
                '''
            }
        }
        // stage('deploy') {
        //     steps {
        //         echo "Deployimg..."
        //         // we can mention multiple linux commands like bellow ('''')
        //         sh '''    
        //         df -h
        //         free -m
        //         '''
        //         echo "PESI"
        //     }
        // }
    }
    // post {
    //     always {
    //         echo "Always do this when pipeline triggered"
    //     }
    //     success {
    //         echo "Run at the time of SUCCESS"
    //     }
    //     failure {
    //         echo "Run at the time of failure"
    //     }
    // }
}