pipeline {
    // agent any
    agent {
        label "Agent-1"
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                sh '''
                    
                    pwd
                    cd 01-VPC
                    ls -ltr
                    terraform init
                '''
                echo "PESI"
            }
        }
        stage('plan') {
            steps {
                sh '''
                    cd 01-VPC
                    terraform plan
                '''
            }
        }
        stage('apply') {
            steps {
                timeout(time: 15, unit: "MINUTES") {
	                    input message: 'Do you want to apply the changes?', ok: 'Yes'
	                }
                echo "terraform apply start"
            }
        }
    }
    // post {
    //     always {
    //         echo "Always do this when pipeline triggered"
    //     }
    //     success {
    //         echo "Run at the time of SUCCESS"
    //     }
    //     failure {
    //         echo "Run at the time of failure"
    //     }
    // }
}